print("Sistemas Hexadecimal = Base 16")
print("0 1 2 3 4 5 6 7 8 9 a b c d e f")
print("0 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15")
print("4ef = 4 * 16**2 + 14 * 16**1 + 15 * 16**0 * 1263")
input()

print("Sistema Octal = Base 8")
print("217= 2 * 8**2+ 1* 8**1 + 7* 8**0 = 143")
input()

print("Python lida bem com todos esses sistemas")
print("Temos até funções pré-definidas em Python para")
print("lidar com isso")
input()

print("Função bin()")
print("Converte um número inteiro em npumero binário")
print("9=",bin(9))
print("Note a string devolvida ,existe um '8b' antes")
print("do inicio do número ,acontece que em Python")
print("existe uma notação para trabalhar com o objeto")
print(type(bin(9)))
print("que representa o número binário")
input()

print("Podemos fazer a volta do bin para inteiro")
print("0b1001=",int("0b1001",2))
print("O segundo argumento do int indica a base do sistema")
print("em que estamos trabalhando,que no caso é 2.")
input()

print("Da mesma forma podemos converter um número")
print("inteiro para o formato de hex por meio da")
print("")